# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7228b90bd8e24c5da18dbb2c7da7ed18d4f785d12e618e999c8eacd180096182d49738dfe15dbbd621a86b4c493fd5777122829a24f101aebbb1f1ba76d302e8

test:
  secret_key_base: 28c5b0bd24ec3f2a9e183cb8e050754b3f74eb69632c78b56a7be69fd7fa242ceba83465e8e01017b2ee31f3c76bc00fda678c61dd019fe5c19a8e4017e7a6f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
